# -*- coding: utf-8 -*-
"""Milestone1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13f-BPszuuU_yggMqSe2ZHTch_8XDaZgN
"""

import ast

class FunctionExtractor(ast.NodeVisitor):
    def __init__(self):
        self.functions = []

    def visit_FunctionDef(self, node):
        self.functions.append(node.name)
        self.generic_visit(node)

class Complexity(ast.NodeVisitor):
    def __init__(self):
        self.complexity = 1

    def visit_If(self, node):
        self.complexity += 1
        self.generic_visit(node)

    def visit_For(self, node):
        self.complexity += 1
        self.generic_visit(node)


class FunctionComplexity(ast.NodeVisitor):
    def __init__(self):
        self.results = {}

    def visit_FunctionDef(self, node):
        counter = Complexity()
        counter.visit(node)
        self.results[node.name] = counter.complexity

code = """
def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    return None

def filter_values(nums):
    result = []
    for n in nums:
        if n % 2 == 0:
            if n > 10:
                result.append(n)
    return result
"""

tree = ast.parse(code)
extractor = FunctionExtractor()
extractor.visit(tree)
print("Functions found:", extractor.functions)


print("\nMissing Documentation:")
for node in ast.walk(tree):
    if isinstance(node, ast.FunctionDef):
        if ast.get_docstring(node) is None:
            print(node.name)


complexity_checker = FunctionComplexity()
complexity_checker.visit(tree)
print("\nFunction Complexity:")
print(complexity_checker.results)

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("all-MiniLM-L6-v2")

code_snippets = [
    "def total(a, b): return a + b",
    "def sum_values(x, y): return x + y",
    "def power(a, b): return a ** b"
]

embeddings = model.encode(code_snippets)
similarity = cosine_similarity(embeddings)

print("\nSemantic Similarity Matrix:")
print(similarity)


# Severity Classification
print("\nSeverity Classification:")
for func, score in complexity_checker.results.items():
    if score > 3:
        print(func, ": WARNING (High Complexity)")
    else:
        print(func, ": INFO")